# SPDX-License-Identifier: BSD-3-Clause
"""Check that ClothDrop targets are generated by release-and-settle physics."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import numpy as np

from gnndom_env import ClothDropConfig, ClothDropRuntimeConfig, ManiFabricClothDropSampler, NewtonClothDropEnv
from gnndom_env.geometry import geometric_target_positions


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate physical target generation for one sampled GNNDOM scene.")
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--seed", type=int, default=43)
    parser.add_argument("--config-id", type=int, default=0)
    parser.add_argument("--cloth-xdim", type=int, default=16)
    parser.add_argument("--cloth-ydim", type=int, default=16)
    parser.add_argument("--cloth-particle-radius", type=float, default=0.00625)
    parser.add_argument("--cloth-mass", type=float, default=0.1)
    parser.add_argument("--cloth-stiffness", type=float, nargs=3, default=(0.9, 1.0, 0.9))
    parser.add_argument("--contact-ke", type=float, default=1.0e5)
    parser.add_argument("--contact-kd", type=float, default=1.0e-2)
    parser.add_argument("--contact-mu", type=float, default=2.0)
    parser.add_argument("--target-type", choices=("flat", "fold", "random"), default="flat")
    parser.add_argument("--x-target", type=float, default=None)
    parser.add_argument("--rot-angle", type=float, default=None)
    parser.add_argument("--env-shape", choices=("None", "platform", "sphere", "rod", "table", "random", "all"), default="sphere")
    parser.add_argument("--shape-size", type=float, nargs="+", default=None)
    parser.add_argument("--shape-pos", type=float, nargs=3, default=None)
    parser.add_argument("--vary-cloth-size", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--vary-stiffness", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--vary-mass", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--vary-orientation", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--fps", type=int, default=60)
    parser.add_argument("--substeps", type=int, default=8)
    parser.add_argument("--iterations", type=int, default=8)
    parser.add_argument("--air-drag", type=float, default=0.0)
    parser.add_argument("--settle-steps", type=int, default=420)
    parser.add_argument("--min-stable-steps", type=int, default=100)
    parser.add_argument("--velocity-threshold", type=float, default=0.03)
    parser.add_argument("--self-contact", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--min-mean-delta", type=float, default=0.002)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    base = ClothDropConfig(
        cloth_particle_radius=args.cloth_particle_radius,
        cloth_size=(args.cloth_xdim, args.cloth_ydim),
        cloth_stiff=tuple(args.cloth_stiffness),
        mass=args.cloth_mass,
        contact_ke=args.contact_ke,
        contact_kd=args.contact_kd,
        contact_mu=args.contact_mu,
        target_type="flat" if args.target_type == "random" else args.target_type,
    )
    sampler = ManiFabricClothDropSampler(
        seed=args.seed,
        base_cfg=base,
        target_type=args.target_type,
        vary_cloth_size=args.vary_cloth_size,
        vary_stiffness=args.vary_stiffness,
        vary_mass=args.vary_mass,
        vary_orientation=args.vary_orientation,
        env_shape=None if args.env_shape == "None" else args.env_shape,
        x_target=args.x_target,
        rot_angle=args.rot_angle,
        shape_size=None if args.shape_size is None else tuple(args.shape_size),
        shape_pos=None if args.shape_pos is None else tuple(args.shape_pos),
    )
    cfg = sampler.sample(args.config_id)
    runtime = ClothDropRuntimeConfig(
        device=args.device,
        fps=args.fps,
        substeps=args.substeps,
        iterations=args.iterations,
        self_contact=args.self_contact,
        air_drag=args.air_drag,
        settle_steps=args.settle_steps,
        velocity_threshold=args.velocity_threshold,
        min_stable_steps=args.min_stable_steps,
    )
    env = NewtonClothDropEnv(cfg, runtime)
    target = env.target_state(force=True)
    physical = np.asarray(target["target_pos"], dtype=np.float32)
    geometric = geometric_target_positions(cfg).astype(np.float32)
    delta = np.linalg.norm(physical - geometric, axis=1)
    z_delta = physical[:, 2] - geometric[:, 2]

    print(
        "[TARGET] "
        f"env_shape={cfg.env_shape} target_type={cfg.target_type} "
        f"contact_ke={cfg.contact_ke:.1f} contact_mu={cfg.contact_mu:.3f} "
        f"source={target['target_source']} release_grasp={int(target['target_release_grasp'])} "
        f"settle_steps={int(target['target_settle_steps'])}"
    )
    print(
        "[TARGET] "
        f"mean_delta={float(np.mean(delta)):.6f} max_delta={float(np.max(delta)):.6f} "
        f"mean_z_delta={float(np.mean(z_delta)):.6f} min_z={float(np.min(physical[:, 2])):.6f} "
        f"max_z={float(np.max(physical[:, 2])):.6f}"
    )
    if cfg.obstacle is not None:
        print(f"[TARGET] obstacle size={cfg.obstacle.shape_size} pos={cfg.obstacle.shape_pos}")

    if cfg.env_shape in {"sphere", "rod", "table"} and float(np.mean(delta)) < float(args.min_mean_delta):
        raise RuntimeError(
            "Physical target is too close to the geometric pre-settle target; "
            "release-and-settle target generation may not be active."
        )
    if int(target["target_release_grasp"]) != 0:
        raise RuntimeError("Target generation must release picker grasp before settling.")


if __name__ == "__main__":
    main()
